### ISSUE TITLE
Add a /project route for the projection page

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#123]
Someone is frustrated by accidentally changing their calibration grid when going to the project page. They suggested a lock calibration feature.

What about starting on the project page? Most people seem to have permanent setups. The calibration can be tested on the project page with the grid overlay so they don't need to go to calibrate to verify the calibration is accurate.

We could have some visual nudge to go to the calibration page if there aren't any calibration points saved in localStorage.

Thoughts?

**Comment by hluedeke** [comment]
Eh, I’m not sure about this one. I think the workflow makes sense to start with calibration. Maybe save a localStorage variable that saves the last place they were? If there is no variable, set the initial mode to calibrate. If the variable is set to “project” then it opens by default to the projection page. Maybe?

**Comment by courtneypattison** [comment]
Like a setting to open on the project page? Or just start on the project page if they have points saved to localStorage? I’m r does some sort of locking make sense? Lol so many questions.

**Comment by roel-v** [comment]
I saw that comment too, IMO the root cause here is 'user is using a trackpad'. Furthermore this issue only happens when the user accidentally *drags* (not even 'clicks') within a certain distance of a corner point. I didn't engage when I saw that comment but from the way it was reported, I really wondered what was going on for this to be such a recurring issue for this user that they saw it warranted to flag is this a 'problem' they're having. I misclick between maximize and close a few times a year too, from how I understood it, that's the category of problem we're talking about here.

Wrt workflow, I think one should double check calibration any time starting the app anyway, even if it's just a glance. I'm not favor of changing it, especially not if this user report is the main justification.

**Comment by hluedeke** [comment]
Good to know, @roel-v. I think what you said makes sense, and I agree that checking calibration every time is a good idea. It keeps the workflow the same every time, and it’s also good for “sanity” in my opinion.

**Comment by courtneypattison** [comment]
I agree with the consistent workflow, calibrate->project. Also, I do feel like this issue is no biggie. I always tweak my corners before projecting, lol. I have been thinking about this for a while though, so it's not completely prompted by that person's report. What about have a `/project` route instead of just the `/calibrate`. Then people who want to start with projecting can bookmark the `/project` route. I probably should've setup the project with a `/calibrate` and `/project` in the first place. I think that was just a poor architecture choice made in haste. We could setup a `layout.tsx` with the header that can be shared between the two. Am I overcomplicating things? Lol, I have a tendency to do that.

**Comment by hluedeke** [comment]
> What about have a /project route instead of just the /calibrate. Then people who want to start with projecting can bookmark the /project route.

That works for me 🤷‍♀️

>  I think that was just a poor architecture choice made in haste.

I wouldn't call your initial architecture poor. It met the needs of the moment. The only time something really ends up being poor is if it dies/does not improve before it solves the problem for the user (which you've already done largely, so I would not put this project in that category). As long as we are learning and growing and improving, I'd say you're doing pretty good!
