### ISSUE TITLE
Set rotate and flip origin based on click/touch

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#124]
I've been thinking about this one for a while but I'm not sure how to make it simple but obvious what it going on. My current thoughts are maybe the cursor on the project page could be a crosshair that slices the screen from top to bottom and left to right so it's obvious that it is doing something special. Then the last place that the user clicks/touches is the origin for the following rotation or flip. That way people can flip on a fold line rather than flipping around the centre of the PDF. I'm not happy with this solution but thought I'd put it out there as an idea.

**Comment by hluedeke** [comment]
My initial thought here is, why not just make the current mouse position the origin and introduce hotkeys for flipping/rotation?

This is an advanced feature anyways, and I feel like advanced users would like pick up what’s going on. An alternative to this would be: make the origin whatever the exact center of the page is. That one doesn’t need hotkeys and feels much more intuitive.

**Comment by hluedeke** [comment]
Yeah…as I think about this…center of the page is what I think most people would expect to happen. It’s unlikely that people are cutting way off in the corners for most cases.

**Comment by courtneypattison** [comment]
The rotation and flips happen from the centre of the PDF right now. My first thought was also to do it based on last click but I think people will feel like the transforms are buggy if they don’t understand where the origin is. The main use case for this one is unwrapping fold lines. It would remove the need for Inkscape for that feature. I feel like there has to be an elegant solution for this one but I can’t think of it.

**Comment by roel-v** [comment]
I used it to unfold a fold line last weekend by cutting the normal shape, mirroring, moving the PDF on screen and also my fabric a bit until everything was where I wanted it to be. Is the problem here that a mirrored piece can end up far away from its original if it's off center on the page? If that's it, I think being able to set a mirror line manually is lot of difficult UI hassle for little gain. Using the current mouse position as the line when a keyboard key is pressed seems, while clever, pretty much undiscoverable to me, and it's not something one uses to often that it becomes ingrained. It also doesn't map to touch devices, which (much to my surprise) a majority of users seem to use (although that's only the impression I get from Facebook, stats may prove me wrong).

Another thought on 'flip along fold line' is that you typically want to flip only one part. For me, real 'projector friendly' patterns (as opposed to 'I also sell the exact same PDF that I also send to the printer for the paper version') have each part in a separate layer, potentially grouped so e.g. have all sizes of the same part connect in some way. In such a case you could flip only the layer, and maybe do "automatic fold line detection" - if one side of the geometry to be flipped (slightly sidestepping the question how is decided what that geometry is), there could be some heuristics on detecting a fold line. Like, if the top/bottom extremes are at the same Y coordinate, assume that side (left or right) is a fold line (and likewise for horizontal fold lines) or maybe even look at the geometry definition itself to see if there is a continuous line between those extremes (I don't know if that information is easily available i.e. if that's technically feasible, just talking UI concepts here). Then again, this all depends on a good mental model of the PDF structure which 95% of users don't have, and for relatively little gain IMO.

**Comment by hluedeke** [comment]
> The rotation and flips happen from the centre of the PDF right now.

The difference in what I am suggesting is using whatever coordinate in the PDF is exactly in the center of the window at the point you click the button becomes the origin, not the center of the pdf itself.

The benefit here, in my opinion, is that the odd doesn’t “jump” around. Whatever is in the center will still be in the center after the transform is applied.

>  Using the current mouse position as the line when a keyboard key is pressed seems, while clever, pretty much undiscoverable to me, and it's not something one uses to often that it becomes ingrained.

Yeah, you’re probably right. I think center of the page origin makes more sense than a constantly changing origin that doesn’t make sense on touch screens anyway. It seemed like a good idea when I wrote it! 😅

**Comment by j-huff** [comment]
Is this all assuming that fold/mirror lines will always be horizontal or vertical? Assuming that mirror lines may sometimes be at weird angles, you could add a "Mirror Line" tool which would work as follows:

(Assume there is some line from point A to point B on the pattern you want to mirror about)

1. The user clicks the Mirror Line tool (or activates it via hotkey)
2. The user clicks point A
3. To indicate that the mirror line tool is active and the first point has been set, draw a line from point A to the cursor position, updating this line as the user moves the cursor.
4. The user clicks point B
5. Using the midpoint of the line between A and B as the origin, mirror the PDF about the angle created by this line.

I feel like that solves what you are trying to achieve here? You could also add the same axis constrained movement via shift key when setting point B, in order to more consistently set vertical and horizontal mirror lines.

**Comment by j-huff** [comment]
Adding in this type of tool makes me feel like it would be prudent to add an "undo" feature as well. If you are relying on the position of PDF, and you mess up when setting your mirror line, it would be nice to be able to quickly go back to the previous PDF position and try again. Might even be nice to be able to set "checkpoints", which would save the position of the PDF for you to be able to swap between several positions. I can't imagine an exact use case for myself for this "checkpoint" system, so it may not be worth the trouble, but if we are storing the position history of the PDF anyway, it may not be too hard to add later on.

**Comment by hluedeke** [comment]
That's an interesting idea @j-huff, and I honestly have no idea how many of (and even if) these projector files would have non-axis abiding lines to mirror. Have we received requests for rotation outside of 90deg constraints @courtneypattison? (same question with mirroring)

To me, requests like that would indicate that we need a more sophisticated tool for mirroring. I do not admittedly have a lot of experience with projector sewing (I think I have cut out 2 patterns so far), so I don't know the answer to this question.

I would hesitate, as @roel-v mentioned earlier, to add a lot of complexity that gives little to no benefit. If we do not see this kind of file often, then I would be hesitant to add a complicated process/tool to the platform. Feel free to disagree! That's my first instinct here, though, is to be cautious. I have questions like: how would you guarantee perfect angle/symmetry? How do you undo/get out of the mode? What state do you reset the PDF to after you are done? Will people understand what is going on and how to get back to "normal"?

I could see this potentially tripping people up, as it is complicated (the same critique I have for my own suggestion of using the mouse coordinates as a reference). If there were many files that needed advanced mirroring, then I would say it's worth looking into.

**Comment by hluedeke** [comment]
> Adding in this type of tool makes me feel like it would be prudent to add an "undo" feature as well. If you are relying on the position of the PDF, and you mess up when setting your mirror line

Ah yes, I agree with you here. There does seem like a need to "reset" somehow. I do like the idea of the tool, I'm just not sure if it is necessary. I really don't know the answer to this, so I could totally be wrong here!

I am a little concerned that if we get too over-optimized/add too many features (and I am guilty of this, certainly!) that we will lose the ease of use/intuitiveness of the tool. Once again, feel free to disagree!

**Comment by j-huff** [comment]
> I am a little concerned that if we get too over-optimized/add too many features (and I am guilty of this, certainly!) that we will lose the ease of use/intuitiveness of the tool. Once again, feel free to disagree!

Definitely agree. There's always the option of being able to set which tools are visible. This is used in slicer software like PrusaSlicer or CURA where the beginner friendly settings are shown by default, but the user can enable intermediate or advanced modes, where more tools and settings become available.

Changing to advanced mode could be done via a simple dropdown-icon-button like the overlay mode selection, or we could have it be done via an open-able settings panel. This could even allow the user to customize their toolbar. Like there's settings presets called beginner, intermediate, advanced, that will change the available tools/toolbar to some configuration we determine. Or, they can select exactly what things to put on the toolbar, and what extra features are enabled.

With the addition of a settings panel like this, you could throw in things like grid snapping settings. This would prevent the toolbar from becoming cluttered with settings that don't get used often.

I know something like this would require significant changes, but in the long run it might help to standardize how toolbar tools function, and would certainly help to prevent feature creep from ruining the simplicity that 95% of users would prefer.

**Comment by hluedeke** [comment]
> I know something like this would require significant changes, but in the long run it might help to standardize how toolbar tools function, and would certainly help to prevent feature creep from ruining the simplicity that 95% of users would prefer.

I agree with you 100% that we need to look at the toolbar tools function and how we separate out basic vs. advanced usage. And yes, I think it's worth looking at this delineation and the hierarchy of tools as a whole.

**Comment by hluedeke** [comment]
I'd go even so far as to say - should we open a new discussion item on categorizing toolsets and planned roadmap items into a beginner/intermediate/advanced structure (or other organizational hierarchy) to help us plan moving forward?

We might still be a little early for this, but that toolbar is definitely starting to get a lot of buttons! I think it would be infinitely easier to program a menu/toolbar structure if we discussed/agreed on a structure ahead of time.

**Comment by courtneypattison** [comment]
OMG I like you folks so much!

I think Sasha would be the best person to talk to about fold lines being non axis abiding. I'll message her.

I don't think we're going to be able to resist adding advanced features. Those are the fun ones lol. So I totally agree we should plan how to add advanced tools without cluttering the UI. I really don't want to frustrate people who just want a simple tool. What do you think would be the best method for planning?

**Comment by hluedeke** [comment]
> OMG I like you folks so much!

Right back atcha! 😉

> I don't think we're going to be able to resist adding advanced features. Those are the fun ones lol.

Touche. lol

> I really don't want to frustrate people who just want a simple tool.

I would guess that most people will fall into this category. It's kind of like Excel. The vast majority of people use probably 10% of the features of Excel. I agree we don't want to complicate it for those folks who just want a simple projection/calibration app.

> What do you think would be the best method for planning?

I'm not sure on this - I was thinking maybe we start a discussion in the Discussions tab? I think the first thing to agree on is "what is the structure we need". It might be beginner/intermediate/advanced, or it might be something else. I think we should talk about it!

> I feel like that solves what you are trying to achieve here?

@j-huff, what if we took your line suggestion, made it an advanced feature, then forced the constraint to be horizontal or 
vertical? This doesn't solve the pixel-hunting problem of "what if I don't get the axis exactly correct", but it at least eliminates the angle variable (if indeed it is ok to eliminate the angle variable). I do think advanced people might appreciate having a "I choose the location of the flip" for convenience, and perhaps this would be the most straightforward way to do this?

**Comment by roel-v** [comment]
Not to be a party pooper here, but I would advocate for restraint when it comes to features that in some sort of way address a potential use case but then in practice are used for only simple things that could have been much more user friendly had they been designed for the more restricted use case. For example, and not that I'm that experienced a sewer, but I have yet to see a pattern that has fold lines that are not horizontal or vertical. Same with an undo stack - are these modification really going to be so big that a 'Reset to initial state' isn't going to cut it? Isn't that a sign that people should edit the pattern and think a little before they get back to the cutting table?

Likewise, these 'progressive complexity' systems seem like a good idea at first, but for me as a user they always devolve into a game of 'let me iteratively increase the complexity level by one and then go on a hunt through all menus to see if way I'm looking for is there'. Because of that, I do not think that such systems with more categories than 'Basic' and 'Advanced' ever work well (that includes in bambu slicer and cura. But also for example FreeSewing, where it's completely opaque (to me) why some settings are under 'basic' and others under 'advanced' (and FS has 5 (!) levels, so I just put it on 'advanced' or whatever the most complex is called and then live with what is essentially developer mode). If PP is going to go the route of working for a bunch of tasks people would/should typically do in a vector editor or on paper (flipping/mirroring to fix up 'cut on fold' patterns, modifying fit by moving seams), I see a slippery slope of moving into a full vector graphics editing system. Because you just know that the next thing is going to be 'how do I export/save my modified PDF'. Would we consider a Bezier tool next? And PDF's just don't have the semantics to make for a real pattern editor anyway, it will always be vector primitives editing at best. I'm old school but I do see and have experienced the appeal of the Unix philosophy of having small tools that do one job well, even if I've also experienced and recognize the convenience of having larger tools with crossover functionality.

Now I already thought this about relatively benign features like increase line thickness and I ended up loving that, so I'm on two minds on this, and I'm mostly just typing this for counterbalance :)

**Comment by courtneypattison** [comment]
I heard back from Sasha and she said the fold lines are only ever on the horizontal and vertical axis.

Roel you're so good at keeping this project grounded!

I'm excited by the idea of being able to customize the top toolbar with just the tools you use, but keeping it with the basics there for people who don't want customization. Mostly because I like customizing things lol. I feel like most sewists would like customizing things too? Purely conjecture.

Maybe we should table this one for now?

The most basic implementation I can think of is: click a button `Set flip origin`, it activates a giant crosshair, click somewhere to place the crosshair, click `flip horizontally` or another available transform, the flip happens at the set origin, then the crosshair disappears.

**Comment by hluedeke** [comment]
@roel-v thank you for sharing this! I agree with you in many ways. I’m one to express skepticism on “do we need it”. And, as mentioned above, I’m also concerned about complexity and this project becoming a slippery slope. 

However, in this one case, I thought about it and decided perhaps this feature wouldn’t be too bad (especially if it was simplified to axes).  I am probably more in favor of just using the center of the window as the transform origin vs the center of the document, but I’m also not the only voice on this project. I can see merit in the other argument (as you mentioned with line thickness). I definitely see the merit of your opinion - I agree with it! Things can absolutely get over complicated (and often do), and then the learning curve increases, despite the designer’s best intentions. People unintentionally engineer their products past the point of peak usefulness.

So I guess where I’m landing here is cautiously supportive. I don’t want to “hamper progress” because I have been wrong on some things, but I am also concerned, as you are, of software bloat.

**Comment by hluedeke** [comment]
I suppose I should mention in the other breath that I also suggested something complicated so I am not immune to outlandish and complex ideas 🤣

**Comment by courtneypattison** [comment]
Okie doke, let's start with the setting the origin to the centre of the screen and maybe progress to setting the origin with a click if people ask for it. We could maybe even setup a hotkey for setting the origin and see if we end up using it. It's only a few lines and wouldn't clutter up the UI. If we use it a lot, then maybe add a button for it.

**Comment by hluedeke** [comment]
> Okie doke, let's start with the setting the origin to the centre of the screen and maybe progress to setting the origin with a click if people ask for it. We could maybe even setup a hotkey for setting the origin and see if we end up using it. It's only a few lines and wouldn't clutter up the UI. If we use it a lot, then maybe add a button for it.

I agree with this approach
