### ISSUE TITLE
Patterns with different margins not working in stitch menu

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#142]
Someone reported that patterns with different margins didn’t work in PP. @roel-v I saw you responded that yours didn’t work either. What was the issue? Maybe it’s something we can fix!

**Comment by roel-v** [comment]
Ah no what this was, was for me (I think, if we're talking about the same Facebook post) actually the pattern for the tailoring ham you also made. I joined the pattern pieces into one before you had the stitching implemented in PP. In that pattern, there isn't really a 'margin' in the traditional sense, it was just two halves on separate pages. Technically I thought I could have just pretended there was like (for example, don't remember the real values) a 7 cm margin at the right of the first page, and an 8 cm left margin on the second and I should be able to get them to line up in PDFStitcher. But I couldn't get that to work close enough to my liking, partly (IIRC) because I couldn't get things to line up because of a lack of granularity in the positioning, and partly because all the lines made things so confusing that I found myself repeatedly painting myself into same corner and then having to undo. Lining them up in Inkscape was way faster for me, and left me with one single A3 PDF to open in PP.

What this user had problems with is (I think) a pattern where the margins aren't the same on all sides, and maybe even between different pages (although I haven't seen her exact pattern). In my opinion the 'right' way of going about this is to shrink each page to fit its content, i.e. removing margins all together, and then piece them together - either with PDFStitcher or manually. Trying to configure this just right, be it in PP or PDFStitcher, will just make someone having to redo this tedious trial and error process every time they want to use this pattern. I didn't get any followup on my reply to her, don't know if she tried.

I haven't used PP's stitch yet, I don't have an opinion on to what extent it should take over manual preprocessing or edge cases like this. I'm probably much more on the 'tough luck - garbage in, garbage out' side than you are, I think you're a saint with how you stay so patient with some users. So yeah don't take my advice on this.

**Comment by courtneypattison** [comment]
Okie doke, I think maybe she just didn't try it in PP, because different sized margins should just add up to an average of the two for an offset in PP. It definitely does get busy though when the pages get blended together. We did the ham in PP and there was quite a bit of text and lines left over.

Lol, I often wish I could hear what you have to say when I read people's posts. I love your take on things. I try to use the principle of charity when interpreting someone's remarks but my initial reaction is always to brush it off!
