### ISSUE TITLE
Add PR checklist 

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#173]
I’d like to put a reminder to yarn build and add to the change log because I keep forgetting to do those. Any other things people would like to be reminded of when submitting a PR?

**Comment by hluedeke** [comment]
Did we add prettier to the build script?
Sent from my iPhone

On Apr 3, 2024, at 5:10 PM, Courtney Pattison ***@***.***> wrote:

﻿

I’d like to put a reminder to yarn build and add to the change log because I keep forgetting to do those. Any other things people would like to be reminded of when submitting a PR?

**Comment by hluedeke** [comment]
Did we add prettier to the build script? If not, it might be nice to add a reminder to run prettier for those who don’t use IDEs.

**Comment by courtneypattison** [comment]
I forgot about that. Thank you for the reminder! I added prettier to the build script to simplify the PR template :)
