### ISSUE TITLE
Calibration canvas is not fixed to screen coordinates

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#203]
We removed fixing the calibration coordinates to screen coordinates as discussed in #15. Then when we stopped showing the grid by default it became a lot less obvious that the calibration only works for full screen or vice versa. I removed the full screen button from the projection page and added an alert/turn on the grid if the full screen mode is exited by using the escape key or some other method in #196. I think we should attempt fixing the canvas to screen coordinates again though!

**Comment by hluedeke** [comment]
I'm confused by this. Are you saying that full screen calibration and normal screen calibration have different scales? Or just different locations? I saw the post in the group about the calibration canvas being a different size in normal mode vs. fullscreen mode. Is that accurate and has that always been the case? If the location moves around, I'd say no big deal, but if the actual scale is off, that's a much bigger problem. It sounds like you've added some measures to help raise awareness of that.

I'm not sure what the benefit of fixing the canvas to the screen coordinates buys us. It definitely creates problems - is there a benefit here I am missing?

**Comment by courtneypattison** [comment]
@hluedeke if someone calibrates in full screen, then the calibration is only accurate in full screen. It’s been that way since screen based coordinates were removed in #15. At the time, it felt ok removing screen coordinates because there were issues with bottom and right toolbars throwing off the calculations. Plus we had the grid shown by default so it was easy to see that the grid was off. Now I’m sure lots of people have the grid turned off by default so it’s not obvious that the calibration is not accurate when toggling full screen.

We need to switch to screen coordinates but that’s really hard to do with bottom and right toolbars. The only thing I can think to do is calculate the client offset on pointer move/down but it doesn’t work well with tablets because you have to wait for them to tap after toggling full screen.

**Comment by sashasewist** [comment]
Question: if the calibration is done in full screen mode, is the calibration then still ok when full screen mode is deactivated when a pattern is open?

Suggestion 1: Could text be added on top of calibration box that says "full screen mode (pic of icon) must be activated for accurate calibration". Then that message disappears when they enter full screen mode. (Maybe repeats when they go back to regular mode on calibration screen?).

Caveats: full screen mode doesn't work for ios devices from my tests, so text wouldn't apply for them,so suggestion 1 not full solution. Also I'm no sure the failsafe of the calibration box being on ever prevented or solved this issue. Once calibrated people have fabric on their mats so many would never see that the calibration box has changed with the full screen issue.

Suggestion 2:
Could a "check calibration" button/process be implemented? This extra button could bring up a dialog box that either explains this full screen issue, or automatically brings the calibration screen to full screen mode of device allows it, tells user to double check that calibration is still accurate, allows user to adjust, and then user clicks "save calibration". This is extra ste, but scale is so essential I don't think people wood be annoyed that there's this double check in place.

Bonus for suggestion 2: as part of the "calibration check" process, the screen could add a diagonal/hypotenuse measurement that user needs to check that ensures they haven't made a measuring error. This is a suggestion I have given to Clinton as well, and I think would go a long way to solve the problem of people using mat measurements that start from 1 instead of 0 that we have seen, and other measuring inaccuracies because they use mat grid instead of tape measure to enter measurements. A diagonal measurement would nicely "force" user to get tape measure to check accuracy, which would then show then any error they have made in their calibration.

**Comment by sashasewist** [comment]
OK, reading your message again Courtney, I see answer to my question is no, full screen calibration will not be accurate for pattern projected in regular mode.
But what about the reverse? If calibrated in regular mode, will pattern still be accurate in full screen mode? I'm guessing no, but if it happens to be yes, then best solution would be to not allow full screen mode when calibrating, and just allow it when projecting pattern.

**Comment by sashasewist** [comment]
Reading #15 , am I to uderstand that this full screen scale issue is only as a result of the fix for multiple screens? If so, the number of users that have mutiple screens is minuscule comapred to the number of people who are affected by this risk of innacurate scale. I would suggest that the fix for multiple screens be removed, so that there's never a risk of this scale problem happening.

**Comment by courtneypattison** [comment]
Sorry, I’m having a when it rains it pours sort of day. My cat is at the vets getting her leg amputated, this issue feels horrible, and my daughter was up in the middle of the night so I’m sleep deprived.

The calibration is only accurate in the same mode it was created in so calibrating in full screen, then switching to regular mode will have inaccurate calibration. You can tell if the calibration is accurate if the grid matches your mat in either calibration or projection mode.

I turned off toggling full screen mode when projecting and if someone exits it there is a pop up that explains and opens the grid overlay. Maybe instead I could have the pop up show up anytime full screen is toggled and have it redirect to the calibration page?

I really like the diagonal measurement idea :)

It’s not just because of multiple screens. It was never working well because the browser location data you can get never accounts for the bottom or right side menu bars/keyboard. I’m still not sure how it can be done well. But I’ll look into it more. I think we can at least do a better job of detecting wether or not there is a mismatch between the screen size when calibrating and projecting. We could save the screen size when calibrating and put up a banner when that size doesn’t match when projecting as a stopgap for the time being.

**Comment by sashasewist** [comment]
That banner sounds like a good way to warn people! 👍🏻
What a sad situation with your cat! I would be losing sleep too. Big hugs for you and your daughter! Don't worry about all this other stuff, it can all wait.

**Comment by courtneypattison** [comment]
> I'm confused by this. Are you saying that full screen calibration and normal screen calibration have different scales? Or just different locations?

Sorry, I did a bad job responding to this. If the calibration grid does not match the mat grid, as happens when toggling full screen (the grid gets shifted up or down), then the perspective transform is happening on the wrong grid location, so the perspective transform is incorrect and the scale is off. Whenever the calibration grid doesn't match the mat grid, the perspective and scale are off.

>I saw the post in the group about the calibration canvas being a different size in normal mode vs. fullscreen mode. Is that accurate and has that always been the case?

Since #15 yes, but it wasn't working well before that either since it didn't take into consideration bottom or right toolbars. I honestly forgot about this issue since I cast from my device I don't use full screen.

>That banner sounds like a good way to warn people! 👍🏻

Ok, I'll see what I can do about this.

>What a sad situation with your cat! I would be losing sleep too. Big hugs for you and your daughter! Don't worry about all this other stuff, it can all wait.

Thank you :)

**Comment by hluedeke** [comment]
In so sorry @courtneypattison 😢 I hope you are able to get some rest tonight, and I hope your cat heals quickly. As @sashasewist said, this stuff can wait! It’s already so useful, and I hope the banner will be enough! I didn’t realize that removing screen coordinates would cause this issue. I appreciate the clarification. Get some rest and worry about this later - you are doing amazing and will get through all this!

**Comment by sashasewist** [comment]
I really like the way you have done the banner and limited the full screen button to only being accessible in Calibrate mode. 👍
I can't believe how quick you have done that. Again, please don't worry about PP while you have more important stuff going on.
I will explain to people in the PfS group this change, and manage questions about it, so you don't have to. ❤️

**Comment by courtneypattison** [comment]
Thank you both so much <3

**Comment by courtneypattison** [comment]
The more I think about this, the less inclined I am to switch to screen coordinates. Although the flow isn't perfect, I think #208 resolves this issue. Here are the limitations that need to be overcome to switch to screen coordinates:
- It's possible to get screen coordinates from any pointer event but screen and client coordinates change over time: window position, multiple monitors, DPR, bottom bars, tabs.
- Calculating where to draw based on screen coordinates is difficult because all of the aforementioned factors need to be considered
- The client offset (screenX - clientX) can be calculated on a pointer event but those are sporadic on touch screens and non-existent for arrow key movements
- Even if we prompted users to get a pointer event to calculate the client offset, it would be inaccurate for multiple monitors since the screenX is across multiple monitors
