### ISSUE TITLE
ChunkLoadError: Loading chunk 440

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#243]
![440943091_10168582570345401_602170416469263563_n](https://github.com/Pattern-Projector/pattern-projector/assets/5465100/9916f43f-d8c7-439b-83ab-6ee040f19950)

**Comment by courtneypattison** [comment]
I've looked into this issue a bit. It seems like what is happening is that the user is on the site when a new version is being deployed so they have a mismatch between the chunks that are loaded. The user can solve the issue by clearing the browser cache and restarting but that's not a great solution. Some suggestions for PP are continuing the serve the old version of the site or never cache the index and calibrate page or stop using chunks? https://rollbar.com/blog/javascript-chunk-load-error/

**Comment by hluedeke** [comment]
Yeah, I'm quite familiar with this one from other projects. However, our upload process is different, so we can maintain older chunks alongside new ones. I'm not sure how vercel handles this. I'm assuming it does a fresh build every time?

You could, in theory, remove chunking because the site is only 2 pages. Without chunking, however, your vendor code (3rd party libraries) would have to load before the site could be shown, and that could slow things down. 

Also, I don't think people have to invalidate their cache, unless your chunks use the same chunk name every time. Most solutions make the chunk names different on every build, so the browser will download the new code every time, even if they have the old chunks cached. If we are reusing the same chunk name(s) for each build, then we should DEFINITELY fix that. That will remove the need for users to refresh their cache, and this becomes a simple browser refresh.

**Comment by courtneypattison** [comment]
> Yeah, I'm quite familiar with this one from other projects. However, my upload process is different, so I can maintain older chunks alongside new ones. I'm not sure how vercel handles this. I'm assuming it only stores the last fresh deployment?
Yeah, unfortunately.

> 
> You could, in theory, remove chunking because the site is only 2 pages. Without chunking, however, your vendor code (3rd party libraries) would have to load before the site could be shown, and that could slow things down.
> 
You're right, best not to use this approach unless we need to!

> Also, I don't think people have to invalidate their cache, unless your chunks use the same chunk name every time. Most solutions make the chunk names different on every build, so the browser will download the new code every time, even if they have the old chunks cached. If we are reusing the same chunk name(s) for each build, then we should DEFINITELY fix that. That will remove the need for users to refresh their cache, and this becomes a simple browser refresh.

I looked into this a bit and I believe webpack uses a `contenthash` for the chunk filenames so they change whenever the content changes. I'm not sure if just a refresh will work. I think the person who had this issue tried that but I don't remember exactly.

Good news is Vercel recently added (skew protection)[https://github.com/orgs/vercel/discussions/812] which I believe solves this issue. I just enabled it for this project so I'm hopeful that this issue is resolved since it's a hard one to duplicate/verify.
