### ISSUE TITLE
Make it more obvious that the calibration grid doesn't need to be the size of the cutting mat

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#27]
I'm getting a lot of messages about people not knowing that they can size their calibration grid to be smaller than their mat and still cut to the edge of the projection area. I'm not sure how to make this more obvious.

Some ideas:
- Remove the border from the projecting grid
- Pad the projecting grid with a few more rows and columns
- Have some sort of tutorial popup or button on the calibration page that explains how to use it
- Reword info page steps

**Comment by hluedeke** [comment]
I think a section in the documentation titled "Choosing a Calibration Size" would be helpful for people who read the documents! Maybe put it near the top because it's one of the first things you have to decide (like even before "Calibration" or as a subheader just under "Calibration" maybe).

I think that would get the point across. There will always be limitations to grid size from a technical perspective, so education seems more straightforward here.

**Comment by courtneypattison** [comment]
I think you're right. I'll try to write something up.

**Comment by hluedeke** [comment]
I've noticed on the FB group that Sasha recommends the calibration grid be at least 16"x24". Maybe include that somewhere? To be honest, I'm very new at projector sewing, haha. I think I've only cut out one pattern using a projector! So I will definitely defer to you on docs here.

**Comment by courtneypattison** [comment]
I think it'd be great to have a number so people will feel confident that they have the minimum grid size. I've only cut one pattern as well! I needed this app working for my cutting setup to make sense and now I've been using all my spare time working on the app instead of sewing, lol!

**Comment by hluedeke** [comment]
> I needed this app working for my cutting setup to make sense and now I've been using all my spare time working on the app instead of sewing, lol!

Same!

**Comment by roel-v** [comment]
Me too except you all are on such a spree that now I can't keep up with either my sewing or the programming 😂

**Comment by roel-v** [comment]
Looking at the Dutch translation which I'm tweaking now, I would put this extra note as a 'step 6' under the 'Calibration' part. It could be something like "6) Tip: if your projector shows an image that is smaller than your cutting mat, that's fine! You can still calibrate the grid on only some of the inner squares on your cutting mat. Your calibration will be more accurate if you make the calibration rectangle as large as possible though, so do try to use as much of your projected area as you can!".

(at least I'm hoping this is the correct interpretation *and* explanation of what you're talking about!)

Furthermore, I think the manual should have something on how to calibrate when you have a transparent cutting mat and need to mark out your own calibration pattern underneath the mat using masking tape. But before I write that, one preliminary issue: I do think that the documentation system with i18n strings will get unwieldy very quickly, as it's quite hard to update strings and keep all translations and newly added strings sync'ed . I do not have experience with more elaborate documentation/translation management systems, does any of you? I think that having the manual (where one wants more more to change things like adding bullet points without touching code) and website/app UI (where such restrictions are less important and even undesirable, you need one string per UI item) in separate systems is more logical. Then again, this would call for a more structured release process, so that translations can be checked, sync'ed and updated at appropriate moments - which I think is not quite appropriate in this stage of the software's life cycle.

Until then, it would at least be nice to have a 'step 6' under 'calibration'.

**Comment by courtneypattison** [comment]
I agree that the internationalization process for the landing page is a bit bonkers. I'm in the process of starting to use weblate for translations. I'm hoping that will simplify the process. The person who provided the danish translation suggested it and it seems like it will be much easier to keep things in sync. Once I get that fully set up I'll add in step 6 and send it to you if that's ok. We can see if it makes things any easier!

**Comment by roel-v** [comment]
Weblate looks amazing, I'd never heard of it. Let's see how it works out.
