### ISSUE TITLE
Add grid calibration boxes

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#63]
Suggestion from PP user: "A button with a couple of boxes like the calibration grid from Projectors for Sewing. To look at after calibration and before loading a pattern, like a final test. Press here and see a 32x32 cm, a 40x60 cm and a 60x80 cm that you can measure yourself. I think it would help people who have used the calibration grid to test size (most current projector sewers, I would think). And people who are unsure if they did it correct. We all know that you cannot test the scale with a small 4 cm square and if the program could show a calibration square instead of the user pulling out the calibration file, I think that would be awesome. I know there is a grid but large friendly boxes easy to measure would be great."

That's supposed to be the purpose of the grid on the "project" page that you can toggle, but they're right that it's not very user friendly. What about making the grid button have different modes like the invert colours button for different sized test rectangles, like the ones from Projectors for Sewing.

**Comment by roel-v** [comment]
I was actually going to suggest this exact thing. I'm not very confident yet in everything (projector, cutting mat, fabric, ...) staying put all the time as I'm cutting, and I've found myself a few times where I wished I could double check the calibration. But because I had my fabric on top, I couldn't see the grid underneath.

What I had in mind myself content-wise is one 10cm (or appropriate equivalent for users having their units set to inch) square in or near each corner (to check skew and other distortions at the edges) and several squares (10, 20, 40 cm? maximum size would have to scale along with the maximum size the user has entered as their reference area i.e. (usually) cutting mat) in the center to check size. And maybe a crosshair on the center, along the entire width and height.

And yes I think it would make sense to put together with show grid button as you say:  state 1: show no overlay, state 2: show grid, state 3: show known size boxes.

**Comment by courtneypattison** [comment]
I planned to add something like this in originally to give people confidence but I couldn't quite figure out how to do it well. I think that's a perfect solution.  Something like [this calibration grid](https://www.google.com/search?sca_esv=02a149adb7727db5&sxsrf=ACQVn0_Dw4VE4NHZaQWaOCpOqNRzLrvyKg:1709557055533&q=calibration+grid+projector+sewing&tbm=isch&source=lnms&sa=X&ved=2ahUKEwj0rZKo1NqEAxV64ckDHZ2QDOoQ0pQJegQIDRAB&biw=1440&bih=779&dpr=2#imgrc=M3XOOHG1dgL7-M) but with 2 inch or 5 cm squares in each corner. Making the rectangles in either cm or in depending on widthxheight preference.

**Comment by j-huff** [comment]
Working on this. I agree with the grid button being used to cycle through multiple overlay modes. The other option is to change the "show grid" button to "show overlay" and a separate input for selecting the overlay mode ("grid + border","border only","calibration sanity check", etc). This secondary input could be a button that cycles through the modes, or a button that opens a drop down menu to select the mode.

**Comment by courtneypattison** [comment]
I like the idea of making the grid button open a drop-down with a few different options. One of the options could be no overlay and could show the grid with slash still. Add lots of functionality without taking up too much space in the menu bar!

**Comment by courtneypattison** [comment]
@j-huff I'm just realizing that I haven't invited you to the organization yet! If you're interested, please send me an email at courtney@patternprojector.com No pressure! It's just nice to be able to self-assign issues. Although I'm pretty bad at remembering to do that!
